{"level":"error","message":"Can not find subscription with clientId 79 subscriptionId 1","timestamp":"2020-05-29T10:24:48.916Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:20:28.537Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:20:33.157Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:21:17.445Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2020-05-29T13:21:43.752Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2020-05-29T13:21:43.753Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2020-05-29T13:21:53.072Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2020-05-29T13:21:53.073Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2020-05-29T13:22:02.089Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2020-05-29T13:22:02.090Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2020-05-29T13:27:59.560Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2020-05-29T13:27:59.561Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2020-05-29T13:28:22.144Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2020-05-29T13:28:22.145Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-05-29T13:29:53.081Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-05-29T13:29:53.081Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-05-29T13:29:53.305Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-05-29T13:29:53.306Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-05-29T13:29:53.355Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-05-29T13:29:53.355Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-05-29T13:29:54.354Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-05-29T13:29:54.355Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2020-05-29T13:29:54.845Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/topologies/server.js:327:35)\n    at emitOne (events.js:115:13)\n    at Pool.emit (events.js:210:7)\n    at Connection.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/pool.js:274:12)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at Socket.<anonymous> (/Users/davidrecheni/Desktop/Repositories/Server/pg-app-i369sswplfvwwaj2y2hjxz0ycuy4q9/node_modules/mongodb-core/lib/connection/connection.js:177:49)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2020-05-29T13:29:54.847Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:38.005Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:38.010Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:38.014Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:38.056Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:39.142Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:39.258Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:39.263Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:39.387Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:39.390Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:37:39.400Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2020-05-29T13:38:32.101Z"}
{"level":"error","message":"Can not find subscription with clientId 1 subscriptionId 4","timestamp":"2020-05-29T13:39:18.109Z"}
{"error":{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\""},"level":"error","message":"Error handling request: ParseError {\n  code: 141,\n  message: 'Invalid function: \"fa_pricing_make_price_proposal\"' }","timestamp":"2020-05-29T13:39:30.931Z"}
{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\"","level":"error","timestamp":"2020-05-29T13:39:30.931Z"}
{"error":{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\""},"level":"error","message":"Error handling request: ParseError {\n  code: 141,\n  message: 'Invalid function: \"fa_pricing_make_price_proposal\"' }","timestamp":"2020-05-29T13:39:32.142Z"}
{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\"","level":"error","timestamp":"2020-05-29T13:39:32.144Z"}
{"error":{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\""},"level":"error","message":"Error handling request: ParseError {\n  code: 141,\n  message: 'Invalid function: \"fa_pricing_make_price_proposal\"' }","timestamp":"2020-05-29T13:39:33.342Z"}
{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\"","level":"error","timestamp":"2020-05-29T13:39:33.344Z"}
{"error":{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\""},"level":"error","message":"Error handling request: ParseError {\n  code: 141,\n  message: 'Invalid function: \"fa_pricing_make_price_proposal\"' }","timestamp":"2020-05-29T13:39:34.144Z"}
{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\"","level":"error","timestamp":"2020-05-29T13:39:34.146Z"}
{"error":{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\""},"level":"error","message":"Error handling request: ParseError {\n  code: 141,\n  message: 'Invalid function: \"fa_pricing_make_price_proposal\"' }","timestamp":"2020-05-29T13:46:46.530Z"}
{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\"","level":"error","timestamp":"2020-05-29T13:46:46.530Z"}
{"error":{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\""},"level":"error","message":"Error handling request: ParseError {\n  code: 141,\n  message: 'Invalid function: \"fa_pricing_make_price_proposal\"' }","timestamp":"2020-05-29T14:06:42.470Z"}
{"code":141,"message":"Invalid function: \"fa_pricing_make_price_proposal\"","level":"error","timestamp":"2020-05-29T14:06:42.471Z"}
